export const browserCoreExamples = [
  "friday browser status",
  "friday browser start",
  "friday browser stop",
  "friday browser tabs",
  "friday browser open https://example.com",
  "friday browser focus abcd1234",
  "friday browser close abcd1234",
  "friday browser screenshot",
  "friday browser screenshot --full-page",
  "friday browser screenshot --ref 12",
  "friday browser snapshot",
  "friday browser snapshot --format aria --limit 200",
  "friday browser snapshot --efficient",
  "friday browser snapshot --labels",
];

export const browserActionExamples = [
  "friday browser navigate https://example.com",
  "friday browser resize 1280 720",
  "friday browser click 12 --double",
  'friday browser type 23 "hello" --submit',
  "friday browser press Enter",
  "friday browser hover 44",
  "friday browser drag 10 11",
  "friday browser select 9 OptionA OptionB",
  "friday browser upload /tmp/file.pdf",
  'friday browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "friday browser dialog --accept",
  'friday browser wait --text "Done"',
  "friday browser evaluate --fn '(el) => el.textContent' --ref 7",
  "friday browser console --level error",
  "friday browser pdf",
];
